# Generated by Django 3.2.4 on 2021-06-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
    ]
